//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDIDataAccess
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// This class represents development_index database table
    /// </summary>
    public partial class development_index
    {
        /// <summary>
        /// test
        /// </summary>
        public int HDI_ID { get; set; }
        public int HDI_Rank { get; set; }
        public string Country { get; set; }
        public double C2010 { get; set; }
        public double C2011 { get; set; }
        public double C2012 { get; set; }
        public double C2013 { get; set; }
        public double C2014 { get; set; }
    }
}
