//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDIDataAccess
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// This class represents suicide_statistics database table
    /// </summary>
    public partial class suicide_statistics
    {
        public int stat_ID { get; set; }
        public string country { get; set; }
        public int year { get; set; }
        public string sex { get; set; }
        public string age { get; set; }
        public string suicides_no { get; set; }
        public Nullable<int> population { get; set; }
    }
}
